# Use o docker-compose apenas em ambiente de desenvolvimento
services:
  postgres:
    container_name: postgres_db
    image: postgres:17.4-bullseye
    # build:
    #   context: ./scripts/database
    #   dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_SUPER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD}
      # POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
