services:
  mysql:
    container_name: job4you_database
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      job4you_network:
          aliases:
            - ${DB_HOST}

  app:
    container_name: job4you_app
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./app:/job4you/app
      - ./public:/job4you/public
      - ./var/cache/doctrine/Proxies:/job4you/var/cache/doctrine/Proxies
    env_file:
      - .env
    networks:
      - job4you_network

volumes:
  db_data:
    driver: local

networks:
  job4you_network:
    driver: bridge